version: '3'
services:
  fast-tmp:
    build: .
    environment:
      FASTAPI_SETTINGS_MODULE : example.settings
    env_file:
      - .rancher_env
    ports:
      - '8001:8000'
    depends_on:
      - redis
      - postgres
    image: fast-tmp
    command: uvicorn example.main:app --port 8000 --host 0.0.0.0
  redis:
    hostname: redis
    image: redis
    volumes:
      - ./redis/data:/data
  postgres:
    hostname: postgres
    image: postgres
    privileged: true
    volumes:
      - ./pg_data/data:/var/lib/postgresql/data/pgdata
